---
- import_playbook: create-hosts.yaml
- import_playbook: bootstrap.yaml
- import_playbook: mongo-shard.yaml
- import_playbook: mongo-config.yaml

- import_playbook: mongo-mongos.yaml
- import_playbook: mongo-cluster.yaml
