---
# tasks file for mongo-config
- name: Create DB path
  become: true
  file:
    path: /data/mongod-config
    owner: mongodb
    state: directory
  notify:
    - start mongod-config
- name: Get the (private) IP address
  with_items: "{{do_networks.v4}}"
  when: item.type == 'private'
  set_fact:
    bind_ip: "{{item.ip_address}}"
- name: Install config file
  become: true
  template: src=mongod-config.conf.j2 dest=/etc/mongod-config.conf
  notify:
    - start mongod-config
- name: Create mongo-data supervisor service
  become: true
  template: src=supervisor-mongod-config.conf.j2 dest=/etc/supervisor/conf.d/mongod-config.conf
  notify:
    - reload supervisor
    - start mongod-config